# Dealing with Inconsistencies in the DataFrame

In [1]:
# import librares
import pandas as pd
import numpy as np

In [11]:
data = pd.DataFrame({
    "Date" : ["2021-12-01", "2021-12-02", "2021-12-03", "2021-12-04", "2021-12-05"],
    "Name" : ["Alice", "Alcie", "Charlie", "Eve", "Eve"],
    "Country" : ["USA", "U.S.A", "United States", "United States of America", "U-S-A"],
    "Sales 2020" : [1000, 1500, 2000, np.nan, 3000],
    "Sales 2021" : [1200, 1800, 2200, 2700, np.nan]
    })

In [12]:
data.head()

         Date     Name                   Country  Sales 2020  Sales 2021
0  2021-12-01    Alice                       USA      1000.0      1200.0
1  2021-12-02    Alcie                     U.S.A      1500.0      1800.0
2  2021-12-03  Charlie             United States      2000.0      2200.0
3  2021-12-04      Eve  United States of America         NaN      2700.0
4  2021-12-05      Eve                     U-S-A      3000.0         NaN

In [13]:
# homonize the name of the country 
customize_country = {"USA" : "United States", "U.S.A" : "United States", "United States of America" : "United States", "U-S-A" : "United States"}
data['Country'] = data['Country'].replace(customize_country)
data.head()

         Date     Name        Country  Sales 2020  Sales 2021
0  2021-12-01    Alice  United States      1000.0      1200.0
1  2021-12-02    Alcie  United States      1500.0      1800.0
2  2021-12-03  Charlie  United States      2000.0      2200.0
3  2021-12-04      Eve  United States         NaN      2700.0
4  2021-12-05      Eve  United States      3000.0         NaN

In [14]:
# correct the name
data['Name'] = data['Name'].replace({"Alcie" : "Alice"})
data.head()

         Date     Name        Country  Sales 2020  Sales 2021
0  2021-12-01    Alice  United States      1000.0      1200.0
1  2021-12-02    Alice  United States      1500.0      1800.0
2  2021-12-03  Charlie  United States      2000.0      2200.0
3  2021-12-04      Eve  United States         NaN      2700.0
4  2021-12-05      Eve  United States      3000.0         NaN

In [17]:
# remove duplicates
data = data.drop_duplicates(subset="Name")
data.head()

         Date     Name        Country  Sales 2020  Sales 2021
0  2021-12-01    Alice  United States      1000.0      1200.0
2  2021-12-03  Charlie  United States      2000.0      2200.0
3  2021-12-04      Eve  United States         NaN      2700.0