# Outliers

In [1]:
# import libraries
import pandas as pd
import numpy as np

In [2]:
data = pd.DataFrame({"weight" : [2.5, 2.7, 2.8, 3.0, 3.2, 3.4, 3.6, 3.8, 4.0, 2.9, 2.4, 3.1, 110.5]})
data.head(13)

    weight
0      2.5
1      2.7
2      2.8
3      3.0
4      3.2
5      3.4
6      3.6
7      3.8
8      4.0
9      2.9
10     2.4
11     3.1
12   110.5

In [3]:
# find mean and std of age column
mean = np.mean(data['weight'])
std = np.std(data['weight'])

print('mean of age is', mean)
print('std of age is', std)

mean of age is 11.376923076923077
std of age is 28.618126419514496

In [4]:
# calculate the Z-Score
data['Z-Score'] = (data['weight']- mean) / std
data.head(13)

    weight   Z-Score
0      2.5 -0.310185
1      2.7 -0.303197
2      2.8 -0.299702
3      3.0 -0.292714
4      3.2 -0.285725
5      3.4 -0.278737
6      3.6 -0.271748
7      3.8 -0.264760
8      4.0 -0.257771
9      2.9 -0.296208
10     2.4 -0.313680
11     3.1 -0.289220
12   110.5  3.463647

In [5]:
# outliers 
print(f"Outliers with threshold 3: \n {data[data['Z-Score'] > 3]}")
print("--------------------------")

# data without outliers
data = data[data['Z-Score'] <= 3]
print(f"data without outliers: \n {data}")

Outliers with threshold 3:
     weight   Z-Score
12   110.5  3.463647
--------------------------
data without outliers:
     weight   Z-Score
0      2.5 -0.310185
1      2.7 -0.303197
2      2.8 -0.299702
3      3.0 -0.292714
4      3.2 -0.285725
5      3.4 -0.278737
6      3.6 -0.271748
7      3.8 -0.264760
8      4.0 -0.257771
9      2.9 -0.296208
10     2.4 -0.313680
11     3.1 -0.289220

In [6]:

# Create the data
data = pd.DataFrame({'Age': [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 50]})

# Calculate the first and third quartile
Q1 = np.percentile(data['Age'], 25, interpolation = 'midpoint')
Q3 = np.percentile(data['Age'], 75, interpolation = 'midpoint')

# Calculate the IQR
IQR = Q3 - Q1

# Calculate the lower and upper bound
lower_bound = Q1 - (1.5 * IQR)
upper_bound = Q3 + (1.5 * IQR)

print(f"Here is the data with outliers:\n {data}")


# Print the outliers
print(f"Here are the outliers based on the IQR threshold:\n {data[(data['Age'] < lower_bound) | (data['Age'] > upper_bound)]}")
print("----------------------------------------")
# Remove the outliers
data = data[(data['Age'] >= lower_bound) & (data['Age'] <= upper_bound)]

print(f"Here is the data without outliers:\n {data}")

Here is the data with outliers:
     Age
0    20
1    21
2    22
3    23
4    24
5    25
6    26
7    27
8    28
9    29
10   30
11   50
Here are the outliers based on the IQR threshold:
     Age
11   50
----------------------------------------
Here is the data without outliers:
     Age
0    20
1    21
2    22
3    23
4    24
5    25
6    26
7    27
8    28
9    29
10   30